//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.ServicePerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePerson.WebServicePersonSoap")]
    public interface WebServicePersonSoap {
        
        // CODEGEN: Generating message contract since element name ListPersonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPerson", ReplyAction="*")]
        WebServiceClient.ServicePerson.ListPersonResponse ListPerson(WebServiceClient.ServicePerson.ListPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServicePerson.ListPersonResponse> ListPersonAsync(WebServiceClient.ServicePerson.ListPersonRequest request);
        
        // CODEGEN: Generating message contract since element name person from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePerson", ReplyAction="*")]
        WebServiceClient.ServicePerson.CreatePersonResponse CreatePerson(WebServiceClient.ServicePerson.CreatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServicePerson.CreatePersonResponse> CreatePersonAsync(WebServiceClient.ServicePerson.CreatePersonRequest request);
        
        // CODEGEN: Generating message contract since element name person from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePerson", ReplyAction="*")]
        WebServiceClient.ServicePerson.UpdatePersonResponse UpdatePerson(WebServiceClient.ServicePerson.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServicePerson.UpdatePersonResponse> UpdatePersonAsync(WebServiceClient.ServicePerson.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePerson", ReplyAction="*")]
        void DeletePerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePerson", ReplyAction="*")]
        System.Threading.Tasks.Task DeletePersonAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPerson", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServicePerson.ListPersonRequestBody Body;
        
        public ListPersonRequest() {
        }
        
        public ListPersonRequest(WebServiceClient.ServicePerson.ListPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListPersonRequestBody {
        
        public ListPersonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServicePerson.ListPersonResponseBody Body;
        
        public ListPersonResponse() {
        }
        
        public ListPersonResponse(WebServiceClient.ServicePerson.ListPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServicePerson.Person[] ListPersonResult;
        
        public ListPersonResponseBody() {
        }
        
        public ListPersonResponseBody(WebServiceClient.ServicePerson.Person[] ListPersonResult) {
            this.ListPersonResult = ListPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePerson", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServicePerson.CreatePersonRequestBody Body;
        
        public CreatePersonRequest() {
        }
        
        public CreatePersonRequest(WebServiceClient.ServicePerson.CreatePersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServicePerson.Person person;
        
        public CreatePersonRequestBody() {
        }
        
        public CreatePersonRequestBody(WebServiceClient.ServicePerson.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServicePerson.CreatePersonResponseBody Body;
        
        public CreatePersonResponse() {
        }
        
        public CreatePersonResponse(WebServiceClient.ServicePerson.CreatePersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreatePersonResponseBody {
        
        public CreatePersonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePerson", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServicePerson.UpdatePersonRequestBody Body;
        
        public UpdatePersonRequest() {
        }
        
        public UpdatePersonRequest(WebServiceClient.ServicePerson.UpdatePersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServicePerson.Person person;
        
        public UpdatePersonRequestBody() {
        }
        
        public UpdatePersonRequestBody(WebServiceClient.ServicePerson.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceClient.ServicePerson.UpdatePersonResponseBody Body;
        
        public UpdatePersonResponse() {
        }
        
        public UpdatePersonResponse(WebServiceClient.ServicePerson.UpdatePersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdatePersonResponseBody {
        
        public UpdatePersonResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePersonSoapChannel : WebServiceClient.ServicePerson.WebServicePersonSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePersonSoapClient : System.ServiceModel.ClientBase<WebServiceClient.ServicePerson.WebServicePersonSoap>, WebServiceClient.ServicePerson.WebServicePersonSoap {
        
        public WebServicePersonSoapClient() {
        }
        
        public WebServicePersonSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePersonSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServicePerson.ListPersonResponse WebServiceClient.ServicePerson.WebServicePersonSoap.ListPerson(WebServiceClient.ServicePerson.ListPersonRequest request) {
            return base.Channel.ListPerson(request);
        }
        
        public WebServiceClient.ServicePerson.Person[] ListPerson() {
            WebServiceClient.ServicePerson.ListPersonRequest inValue = new WebServiceClient.ServicePerson.ListPersonRequest();
            inValue.Body = new WebServiceClient.ServicePerson.ListPersonRequestBody();
            WebServiceClient.ServicePerson.ListPersonResponse retVal = ((WebServiceClient.ServicePerson.WebServicePersonSoap)(this)).ListPerson(inValue);
            return retVal.Body.ListPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServicePerson.ListPersonResponse> WebServiceClient.ServicePerson.WebServicePersonSoap.ListPersonAsync(WebServiceClient.ServicePerson.ListPersonRequest request) {
            return base.Channel.ListPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServicePerson.ListPersonResponse> ListPersonAsync() {
            WebServiceClient.ServicePerson.ListPersonRequest inValue = new WebServiceClient.ServicePerson.ListPersonRequest();
            inValue.Body = new WebServiceClient.ServicePerson.ListPersonRequestBody();
            return ((WebServiceClient.ServicePerson.WebServicePersonSoap)(this)).ListPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServicePerson.CreatePersonResponse WebServiceClient.ServicePerson.WebServicePersonSoap.CreatePerson(WebServiceClient.ServicePerson.CreatePersonRequest request) {
            return base.Channel.CreatePerson(request);
        }
        
        public void CreatePerson(WebServiceClient.ServicePerson.Person person) {
            WebServiceClient.ServicePerson.CreatePersonRequest inValue = new WebServiceClient.ServicePerson.CreatePersonRequest();
            inValue.Body = new WebServiceClient.ServicePerson.CreatePersonRequestBody();
            inValue.Body.person = person;
            WebServiceClient.ServicePerson.CreatePersonResponse retVal = ((WebServiceClient.ServicePerson.WebServicePersonSoap)(this)).CreatePerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServicePerson.CreatePersonResponse> WebServiceClient.ServicePerson.WebServicePersonSoap.CreatePersonAsync(WebServiceClient.ServicePerson.CreatePersonRequest request) {
            return base.Channel.CreatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServicePerson.CreatePersonResponse> CreatePersonAsync(WebServiceClient.ServicePerson.Person person) {
            WebServiceClient.ServicePerson.CreatePersonRequest inValue = new WebServiceClient.ServicePerson.CreatePersonRequest();
            inValue.Body = new WebServiceClient.ServicePerson.CreatePersonRequestBody();
            inValue.Body.person = person;
            return ((WebServiceClient.ServicePerson.WebServicePersonSoap)(this)).CreatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServicePerson.UpdatePersonResponse WebServiceClient.ServicePerson.WebServicePersonSoap.UpdatePerson(WebServiceClient.ServicePerson.UpdatePersonRequest request) {
            return base.Channel.UpdatePerson(request);
        }
        
        public void UpdatePerson(WebServiceClient.ServicePerson.Person person) {
            WebServiceClient.ServicePerson.UpdatePersonRequest inValue = new WebServiceClient.ServicePerson.UpdatePersonRequest();
            inValue.Body = new WebServiceClient.ServicePerson.UpdatePersonRequestBody();
            inValue.Body.person = person;
            WebServiceClient.ServicePerson.UpdatePersonResponse retVal = ((WebServiceClient.ServicePerson.WebServicePersonSoap)(this)).UpdatePerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServicePerson.UpdatePersonResponse> WebServiceClient.ServicePerson.WebServicePersonSoap.UpdatePersonAsync(WebServiceClient.ServicePerson.UpdatePersonRequest request) {
            return base.Channel.UpdatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServicePerson.UpdatePersonResponse> UpdatePersonAsync(WebServiceClient.ServicePerson.Person person) {
            WebServiceClient.ServicePerson.UpdatePersonRequest inValue = new WebServiceClient.ServicePerson.UpdatePersonRequest();
            inValue.Body = new WebServiceClient.ServicePerson.UpdatePersonRequestBody();
            inValue.Body.person = person;
            return ((WebServiceClient.ServicePerson.WebServicePersonSoap)(this)).UpdatePersonAsync(inValue);
        }
        
        public void DeletePerson(int id) {
            base.Channel.DeletePerson(id);
        }
        
        public System.Threading.Tasks.Task DeletePersonAsync(int id) {
            return base.Channel.DeletePersonAsync(id);
        }
    }
}
